### ISSUE TITLE
Space in source Directory input path are not escaped 

### ISSUE THREAD

**Issue by andreacapriplexure** [piraces/azure-devops-bicep-task#1]
This is my steps
```
steps:
- task: BicepInstall@0
- task: BicepBuild@0
  inputs:
    sourceDirectory: "D://Arm Templates/deploy.bicep'"
```
