### ISSUE TITLE
Bicep Build Task ability to recurse the entire directory tree

### ISSUE THREAD

**Issue by brekus** [piraces/azure-devops-bicep-task#5]
Currently the task allows you to set a directory of bicep files. It would be nice if the task could recurse a whole directory tree and convert any bicep file it finds and output to the same directory.

**Comment by piraces** [comment]
Hello @brekus , thank you for the suggestion.

I will work on this as a new feature as soon as possible.

Thanks!

**Comment by piraces** [comment]
Hello again @brekus .

Sorry I was confused about your issue comment, but currently the extension can already do this thanks to supporting [glob expressions](https://en.wikipedia.org/wiki/Glob_(programming)).

In order to show how to recurse a whole directory tree and convert any bicep file it finds (output in the same directory), I have setup a task to the testing pipeline with you can see [here](https://raulejea.visualstudio.com/Bicep%20Tasks/_build/results?buildId=261&view=logs&j=295e7618-5d04-5731-f417-e49cf049e2b1&t=4cd1a08e-b378-5f2b-3972-9c2648a5570e).

The task is the following:
```
- task: BicepBuild@0
  displayName: 'Compile Sample .bicep files test (all in entire directory tree with glob)'
  inputs:
    sourceDirectory: '**/**.bicep'
```

The specified source directory makes the extension recurse all entire directory tree (including all subfolders) and making the behavior you explained.

`**/**.bicep` Glob will get all `.bicep` files in all directories.

I will close the issue, but if I misunderstood your initial idea, feel free to reopen it 👍
